#![allow(non_camel_case_types)]

use serde::{Deserialize, Serialize};
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
pub enum SupportedKeys {
    KC_NO,
    KC_ESC,
    KC_1,
    KC_2,
    KC_3,
    KC_4,
    KC_5,
    KC_6,
    KC_7,
    KC_8,
    KC_9,
    KC_0,
    KC_MINUS,
    KC_EQUAL,
    KC_BACKSPACE,
    KC_TAB,
    KC_Q,
    KC_W,
    KC_E,
    KC_R,
    KC_T,
    KC_Y,
    KC_U,
    KC_I,
    KC_O,
    KC_P,
    KC_LEFTBRACE,
    KC_RIGHTBRACE,
    KC_ENTER,
    KC_LEFTCTRL,
    KC_A,
    KC_S,
    KC_D,
    KC_F,
    KC_G,
    KC_H,
    KC_J,
    KC_K,
    KC_L,
    KC_SEMICOLON,
    KC_APOSTROPHE,
    KC_GRAVE,
    KC_LEFTSHIFT,
    KC_BACKSLASH,
    KC_Z,
    KC_X,
    KC_C,
    KC_V,
    KC_B,
    KC_N,
    KC_M,
    KC_COMMA,
    KC_DOT,
    KC_SLASH,
    KC_RIGHTSHIFT,
    KC_KPASTERISK,
    KC_LEFTALT,
    KC_SPACE,
    KC_CAPSLOCK,
    KC_F1,
    KC_F2,
    KC_F3,
    KC_F4,
    KC_F5,
    KC_F6,
    KC_F7,
    KC_F8,
    KC_F9,
    KC_F10,
    KC_NUMLOCK,
    KC_SCROLLLOCK,
    KC_KP7,
    KC_KP8,
    KC_KP9,
    KC_KPMINUS,
    KC_KP4,
    KC_KP5,
    KC_KP6,
    KC_KPPLUS,
    KC_KP1,
    KC_KP2,
    KC_KP3,
    KC_KP0,
    KC_KPDOT,

    KC_ZENKAKUHANKAKU,
    KC_102ND,
    KC_F11,
    KC_F12,
    KC_RO,
    KC_KATAKANA,
    KC_HIRAGANA,
    KC_HENKAN,
    KC_KATAKANAHIRAGANA,
    KC_MUHENKAN,
    KC_KPJPCOMMA,
    KC_KPENTER,
    KC_RIGHTCTRL,
    KC_KPSLASH,
    KC_SYSRQ,
    KC_RIGHTALT,
    KC_LINEFEED,
    KC_HOME,
    KC_UP,
    KC_PAGEUP,
    KC_LEFT,
    KC_RIGHT,
    KC_END,
    KC_DOWN,
    KC_PAGEDOWN,
    KC_INSERT,
    KC_DELETE,
    KC_MACRO,
    KC_MUTE,
    KC_VOLUMEDOWN,
    KC_VOLUMEUP,
    KC_POWER,
    KC_KPEQUAL,
    KC_KPPLUSMINUS,
    KC_PAUSE,
    KC_SCALE,

    KC_KPCOMMA,
    KC_HANGEUL,
    KC_HANGUEL,
    KC_HANJA,
    KC_YEN,
    KC_LEFTMETA,
    KC_RIGHTMETA,
    KC_COMPOSE,

    KC_STOP,
    KC_AGAIN,
    KC_PROPS,
    KC_UNDO,
    KC_FRONT,
    KC_COPY,
    KC_OPEN,
    KC_PASTE,
    KC_FIND,
    KC_CUT,
    KC_HELP,
    KC_MENU,
    KC_CALC,
    KC_SETUP,
    KC_SLEEP,
    KC_WAKEUP,
    KC_FILE,
    KC_SENDFILE,
    KC_DELETEFILE,
    KC_XFER,
    KC_PROG1,
    KC_PROG2,
    KC_WWW,
    KC_MSDOS,
    KC_COFFEE,
    KC_SCREENLOCK,
    KC_ROTATE_DISPLAY,
    KC_DIRECTION,
    KC_CYCLEWINDOWS,
    KC_MAIL,
    KC_BOOKMARKS,
    KC_COMPUTER,
    KC_BACK,
    KC_FORWARD,
    KC_CLOSECD,
    KC_EJECTCD,
    KC_EJECTCLOSECD,
    KC_NEXTSONG,
    KC_PLAYPAUSE,
    KC_PREVIOUSSONG,
    KC_STOPCD,
    KC_RECORD,
    KC_REWIND,
    KC_PHONE,
    KC_ISO,
    KC_CONFIG,
    KC_HOMEPAGE,
    KC_REFRESH,
    KC_EXIT,
    KC_MOVE,
    KC_EDIT,
    KC_SCROLLUP,
    KC_SCROLLDOWN,
    KC_KPLEFTPAREN,
    KC_KPRIGHTPAREN,
    KC_NEW,
    KC_REDO,

    KC_F13,
    KC_F14,
    KC_F15,
    KC_F16,
    KC_F17,
    KC_F18,
    KC_F19,
    KC_F20,
    KC_F21,
    KC_F22,
    KC_F23,
    KC_F24,

    KC_PLAYCD,
    KC_PAUSECD,
    KC_PROG3,
    KC_PROG4,
    KC_ALL_APPLICATIONS,
    KC_DASHBOARD,
    KC_SUSPEND,
    KC_CLOSE,
    KC_PLAY,
    KC_FASTFORWARD,
    KC_BASSBOOST,
    KC_PRINT,
    KC_HP,
    KC_CAMERA,
    KC_SOUND,
    KC_QUESTION,
    KC_EMAIL,
    KC_CHAT,
    KC_SEARCH,
    KC_CONNECT,
    KC_FINANCE,
    KC_SPORT,
    KC_SHOP,
    KC_ALTERASE,
    KC_CANCEL,
    KC_BRIGHTNESSDOWN,
    KC_BRIGHTNESSUP,
    KC_MEDIA,

    KC_SWITCHVIDEOMODE,
    KC_KBDILLUMTOGGLE,
    KC_KBDILLUMDOWN,
    KC_KBDILLUMUP,

    KC_SEND,
    KC_REPLY,
    KC_FORWARDMAIL,
    KC_SAVE,
    KC_DOCUMENTS,

    KC_BATTERY,

    KC_BLUETOOTH,
    KC_WLAN,
    KC_UWB,

    KC_UNKNOWN,

    KC_VIDEO_NEXT,
    KC_VIDEO_PREV,
    KC_BRIGHTNESS_CYCLE,
    KC_BRIGHTNESS_AUTO,
    KC_BRIGHTNESS_ZERO,
    KC_DISPLAY_OFF,

    KC_WWAN,
    KC_WIMAX,
    KC_RFKILL,

    KC_MICMUTE,
    CLOSE,
    LAYER(u8),
}
impl SupportedKeys {
    pub fn as_key_code(&self) -> u8 {
        use SupportedKeys::*;
        match self {
            KC_NO => 0,
            KC_ESC => 1,
            KC_1 => 2,
            KC_2 => 3,
            KC_3 => 4,
            KC_4 => 5,
            KC_5 => 6,
            KC_6 => 7,
            KC_7 => 8,
            KC_8 => 9,
            KC_9 => 10,
            KC_0 => 11,
            KC_MINUS => 12,
            KC_EQUAL => 13,
            KC_BACKSPACE => 14,
            KC_TAB => 15,
            KC_Q => 16,
            KC_W => 17,
            KC_E => 18,
            KC_R => 19,
            KC_T => 20,
            KC_Y => 21,
            KC_U => 22,
            KC_I => 23,
            KC_O => 24,
            KC_P => 25,
            KC_LEFTBRACE => 26,
            KC_RIGHTBRACE => 27,
            KC_ENTER => 28,
            KC_LEFTCTRL => 29,
            KC_A => 30,
            KC_S => 31,
            KC_D => 32,
            KC_F => 33,
            KC_G => 34,
            KC_H => 35,
            KC_J => 36,
            KC_K => 37,
            KC_L => 38,
            KC_SEMICOLON => 39,
            KC_APOSTROPHE => 40,
            KC_GRAVE => 41,
            KC_LEFTSHIFT => 42,
            KC_BACKSLASH => 43,
            KC_Z => 44,
            KC_X => 45,
            KC_C => 46,
            KC_V => 47,
            KC_B => 48,
            KC_N => 49,
            KC_M => 50,
            KC_COMMA => 51,
            KC_DOT => 52,
            KC_SLASH => 53,
            KC_RIGHTSHIFT => 54,
            KC_KPASTERISK => 55,
            KC_LEFTALT => 56,
            KC_SPACE => 57,
            KC_CAPSLOCK => 58,
            KC_F1 => 59,
            KC_F2 => 60,
            KC_F3 => 61,
            KC_F4 => 62,
            KC_F5 => 63,
            KC_F6 => 64,
            KC_F7 => 65,
            KC_F8 => 66,
            KC_F9 => 67,
            KC_F10 => 68,
            KC_NUMLOCK => 69,
            KC_SCROLLLOCK => 70,
            KC_KP7 => 71,
            KC_KP8 => 72,
            KC_KP9 => 73,
            KC_KPMINUS => 74,
            KC_KP4 => 75,
            KC_KP5 => 76,
            KC_KP6 => 77,
            KC_KPPLUS => 78,
            KC_KP1 => 79,
            KC_KP2 => 80,
            KC_KP3 => 81,
            KC_KP0 => 82,
            KC_KPDOT => 83,
            KC_ZENKAKUHANKAKU => 85,
            KC_102ND => 86,
            KC_F11 => 87,
            KC_F12 => 88,
            KC_RO => 89,
            KC_KATAKANA => 90,
            KC_HIRAGANA => 91,
            KC_HENKAN => 92,
            KC_KATAKANAHIRAGANA => 93,
            KC_MUHENKAN => 94,
            KC_KPJPCOMMA => 95,
            KC_KPENTER => 96,
            KC_RIGHTCTRL => 97,
            KC_KPSLASH => 98,
            KC_SYSRQ => 99,
            KC_RIGHTALT => 100,
            KC_LINEFEED => 101,
            KC_HOME => 102,
            KC_UP => 103,
            KC_PAGEUP => 104,
            KC_LEFT => 105,
            KC_RIGHT => 106,
            KC_END => 107,
            KC_DOWN => 108,
            KC_PAGEDOWN => 109,
            KC_INSERT => 110,
            KC_DELETE => 111,
            KC_MACRO => 112,
            KC_MUTE => 113,
            KC_VOLUMEDOWN => 114,
            KC_VOLUMEUP => 115,
            KC_POWER => 116,
            KC_KPEQUAL => 117,
            KC_KPPLUSMINUS => 118,
            KC_PAUSE => 119,
            KC_SCALE => 120,
            KC_KPCOMMA => 121,
            KC_HANGEUL => 122,
            KC_HANJA => 123,
            KC_YEN => 124,
            KC_LEFTMETA => 125,
            KC_RIGHTMETA => 126,
            KC_COMPOSE => 127,
            KC_STOP => 128,
            KC_AGAIN => 129,
            KC_PROPS => 130,
            KC_UNDO => 131,
            KC_FRONT => 132,
            KC_COPY => 133,
            KC_OPEN => 134,
            KC_PASTE => 135,
            KC_FIND => 136,
            KC_CUT => 137,
            KC_HELP => 138,
            KC_MENU => 139,
            KC_CALC => 140,
            KC_SETUP => 141,
            KC_SLEEP => 142,
            KC_WAKEUP => 143,
            KC_FILE => 144,
            KC_SENDFILE => 145,
            KC_DELETEFILE => 146,
            KC_XFER => 147,
            KC_PROG1 => 148,
            KC_PROG2 => 149,
            KC_WWW => 150,
            KC_MSDOS => 151,
            KC_COFFEE => 152,
            KC_ROTATE_DISPLAY => 153,
            KC_CYCLEWINDOWS => 154,
            KC_MAIL => 155,
            KC_BOOKMARKS => 156,
            KC_COMPUTER => 157,
            KC_BACK => 158,
            KC_FORWARD => 159,
            KC_CLOSECD => 160,
            KC_EJECTCD => 161,
            KC_EJECTCLOSECD => 162,
            KC_NEXTSONG => 163,
            KC_PLAYPAUSE => 164,
            KC_PREVIOUSSONG => 165,
            KC_STOPCD => 166,
            KC_RECORD => 167,
            KC_REWIND => 168,
            KC_PHONE => 169,
            KC_ISO => 170,
            KC_CONFIG => 171,
            KC_HOMEPAGE => 172,
            KC_REFRESH => 173,
            KC_EXIT => 174,
            KC_MOVE => 175,
            KC_EDIT => 176,
            KC_SCROLLUP => 177,
            KC_SCROLLDOWN => 178,
            KC_KPLEFTPAREN => 179,
            KC_KPRIGHTPAREN => 180,
            KC_NEW => 181,
            KC_REDO => 182,
            KC_F13 => 183,
            KC_F14 => 184,
            KC_F15 => 185,
            KC_F16 => 186,
            KC_F17 => 187,
            KC_F18 => 188,
            KC_F19 => 189,
            KC_F20 => 190,
            KC_F21 => 191,
            KC_F22 => 192,
            KC_F23 => 193,
            KC_F24 => 194,
            KC_PLAYCD => 200,
            KC_PAUSECD => 201,
            KC_PROG3 => 202,
            KC_PROG4 => 203,
            KC_ALL_APPLICATIONS => 204,
            KC_SUSPEND => 205,
            KC_CLOSE => 206,
            KC_PLAY => 207,
            KC_FASTFORWARD => 208,
            KC_BASSBOOST => 209,
            KC_PRINT => 210,
            KC_HP => 211,
            KC_CAMERA => 212,
            KC_SOUND => 213,
            KC_QUESTION => 214,
            KC_EMAIL => 215,
            KC_CHAT => 216,
            KC_SEARCH => 217,
            KC_CONNECT => 218,
            KC_FINANCE => 219,
            KC_SPORT => 220,
            KC_SHOP => 221,
            KC_ALTERASE => 222,
            KC_CANCEL => 223,
            KC_BRIGHTNESSDOWN => 224,
            KC_BRIGHTNESSUP => 225,
            KC_MEDIA => 226,
            KC_SWITCHVIDEOMODE => 227,
            KC_KBDILLUMTOGGLE => 228,
            KC_KBDILLUMDOWN => 229,
            KC_KBDILLUMUP => 230,
            KC_SEND => 231,
            KC_REPLY => 232,
            KC_FORWARDMAIL => 233,
            KC_SAVE => 234,
            KC_DOCUMENTS => 235,
            KC_BATTERY => 236,
            KC_BLUETOOTH => 237,
            KC_WLAN => 238,
            KC_UWB => 239,
            KC_UNKNOWN => 240,
            KC_VIDEO_NEXT => 241,
            KC_VIDEO_PREV => 242,
            KC_BRIGHTNESS_CYCLE => 243,
            KC_BRIGHTNESS_AUTO => 244,
            KC_DISPLAY_OFF => 245,
            KC_WWAN => 246,
            KC_RFKILL => 247,
            KC_MICMUTE => 248,
            KC_HANGUEL => KC_HANGEUL.as_key_code(),
            KC_SCREENLOCK => KC_COFFEE.as_key_code(),
            KC_DIRECTION => KC_ROTATE_DISPLAY.as_key_code(),
            KC_DASHBOARD => KC_ALL_APPLICATIONS.as_key_code(),
            KC_BRIGHTNESS_ZERO => KC_BRIGHTNESS_AUTO.as_key_code(),
            KC_WIMAX => KC_WWAN.as_key_code(),
            CLOSE => 0,
            LAYER(_) => 0,
        }
    }

    pub fn is_mod_key(&self) -> bool {
        use SupportedKeys::*;
        matches!(
            self,
            KC_LEFTCTRL
                | KC_RIGHTCTRL
                | KC_LEFTMETA
                | KC_RIGHTMETA
                | KC_LEFTSHIFT
                | KC_RIGHTSHIFT
                | KC_LEFTALT
                | KC_RIGHTALT
        )
    }

    pub fn is_lock_key(&self) -> bool {
        use SupportedKeys::*;
        matches!(self, KC_CAPSLOCK | KC_NUMLOCK | Self::KC_SCROLLLOCK)
    }
}
